services:
  penguin-pass:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.penguin.entrypoints=web, websecure"
      - "traefik.http.routers.penguin.rule=Host(`${PENGUIN_SERVICE:-penguin}.${DOMAIN}`)"
      - "traefik.http.routers.penguin.tls=true"
      - "traefik.http.routers.penguin.tls.certresolver=cloudflare"
      - "traefik.http.services.penguin.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.penguin.middlewares=secured@file"

      # Homepage Dashboard Labels
      - "homepage.group=${PENGUIN_GROUP:-Services}"
      - "homepage.name=${PENGUIN_SERVICE_NAME:-Penguin Pass}"
      - "homepage.icon=password.png"
      - "homepage.href=https://${PENGUIN_SERVICE:-penguin}.${DOMAIN}/"
      - "homepage.description=${PENGUIN_DESCRIPTION:-Password generator}"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
